# Generated by Django 5.1.7 on 2025-04-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_amount_surveys_ammount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveys",
            name="HourlyAmmount",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
