# Generated by Django 5.1.7 on 2025-04-11 14:27

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_surveys_hourlyammount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveys",
            name="Ammount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0.0"),
                default_currency="USD",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="surveys",
            name="NTEPrice",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0.0"),
                default_currency="USD",
                max_digits=10,
            ),
        ),
    ]
