# Generated by Django 5.1.7 on 2025-04-11 14:29

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_surveys_ammount_alter_surveys_nteprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveys",
            name="Ammount",
            field=djmoney.models.fields.MoneyField(
                blank=True, decimal_places=2, default_currency="USD", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="surveys",
            name="NTEPrice",
            field=djmoney.models.fields.MoneyField(
                blank=True, decimal_places=2, default_currency="USD", max_digits=10
            ),
        ),
    ]
